# Generated by Django 3.2.4 on 2021-06-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_schooling'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='schooling',
        ),
        migrations.AddField(
            model_name='resume',
            name='tenth_schooling',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='resume',
            name='twelveth_schooling',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='resume',
            name='university',
            field=models.CharField(max_length=300),
        ),
    ]
